"""
Post-training quantization of LeNet-5 to int8 and export as C headers.
Target format:
  - Weights: symmetric int8 (Q0.7) scaled to [-127, 127]
  - Biases: int32 (scaled accordingly)
  - Activations: int8 (Q5.3) range [0, 15.875] for ReLU outputs

Exports:
  - hls/weights/c1_w.h, c1_b.h
  - hls/weights/c3_w.h, c3_b.h
  - hls/weights/c5_w.h, c5_b.h
  - hls/weights/f6_w.h, f6_b.h
  - hls/weights/out_w.h, out_b.h
  - Test vectors and golden reference outputs
"""

import torch
import torch.nn.functional as F
import numpy as np
import os
import sys
import json

from lenet5_model import LeNet5


# HLS fixed-point format config
# Weight format: Q0.7 (symmetric int8, range [-1.0, +1.0) in float)
#   quant_w = round(w / w_scale) where w_scale = max(|w|) / 127
# Activation format: Q5.3 (int8, range [0, 15.875] for ReLU output)
#   quant_a = clamp(round(a / a_scale), 0, 127)
# Accumulator: int32, accumulation of w_quant * a_quant
#   After accumulation: result >> 3 to convert back to Q5.3
WEIGHT_BITS = 8
ACT_BITS = 8
ACCUM_BITS = 32

WEIGHTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'hls', 'weights')
MODEL_PATH = 'float32_lenet5.pth'


def load_model(model_path):
    """Load trained float32 model."""
    model = LeNet5()
    checkpoint = torch.load(model_path, map_location='cpu', weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    print(f"Loaded model from {model_path}")
    print(f"  Epoch: {checkpoint['epoch']}, Test accuracy: {checkpoint['test_accuracy']:.2f}%")
    return model


def quantize_weight_tensor(w):
    """Quantize weight tensor to symmmetric int8.
    Returns: q_w (int8 numpy), scale (float)
    """
    w_np = w.detach().cpu().numpy()
    w_max = np.max(np.abs(w_np))
    if w_max == 0:
        scale = 1.0
    else:
        scale = w_max / 127.0
    q_w = np.clip(np.round(w_np / scale), -127, 127).astype(np.int8)
    return q_w, scale


def quantize_bias_tensor(b, w_scale, a_scale):
    """Quantize bias to int32 considering weight and activation scales.
    bias_quant = round(bias_float / (w_scale * a_scale))
    """
    b_np = b.detach().cpu().numpy()
    scale_product = w_scale * a_scale
    q_b = np.round(b_np / scale_product).astype(np.int32)
    return q_b


def dequantize_weight(q_w, scale):
    """Dequantize weight for verification."""
    return q_w.astype(np.float32) * scale


def c_array_str(arr, name, dtype='int8_t', per_line=16):
    """Format numpy array as C array string using ap_int types for Vitis HLS."""
    lines = []
    lines.append(f'// Auto-generated by quantize_export.py')
    lines.append(f'// {name}: shape {arr.shape}, dtype {arr.dtype}')
    flat = arr.flatten()
    total = len(flat)

    # Use ap_int types for Vitis HLS compatibility
    if dtype == 'int8_t':
        lines.append(f'const ap_int<8> {name}[{total}] = {{')
        val_strs = [str(int(v)) for v in flat]
    elif dtype == 'int32_t':
        lines.append(f'const ap_int<32> {name}[{total}] = {{')
        val_strs = [str(int(v)) for v in flat]
    else:
        lines.append(f'const {dtype} {name}[{total}] = {{')
        val_strs = [str(v) for v in flat]

    for i in range(0, len(val_strs), per_line):
        chunk = val_strs[i:i+per_line]
        lines.append('    ' + ', '.join(chunk) + ',')
    lines.append('};')
    lines.append('')
    return '\n'.join(lines)


def write_weight_header(filename, arrays):
    """Write a weight header file with C arrays."""
    with open(filename, 'w') as f:
        f.write('// Auto-generated LeNet-5 weight file\n')
        f.write('// Do not edit manually\n')
        f.write('#pragma once\n\n')
        f.write('#include <ap_int.h>\n\n')
        for arr in arrays:
            f.write(c_array_str(**arr))
    print(f"  Wrote: {filename} ({len(arrays)} arrays)")


# Calibration activations - need to track the range of each layer's output
class ActivationObserver:
    """Track min/max of activations per layer."""
    def __init__(self):
        self.ranges = {}  # name -> (min_val, max_val)

    def observe(self, name, tensor):
        t_np = tensor.detach().cpu().numpy()
        t_min = float(np.min(t_np))
        t_max = float(np.max(t_np))
        if name not in self.ranges:
            self.ranges[name] = (t_min, t_max)
        else:
            prev_min, prev_max = self.ranges[name]
            self.ranges[name] = (min(prev_min, t_min), max(prev_max, t_max))

    def get_scale(self, name):
        """Get Q5.3 scale for a ReLU activation layer."""
        if name not in self.ranges:
            return 1.0 / 8.0  # default
        _, t_max = self.ranges[name]
        if t_max <= 0:
            return 1.0 / 8.0
        # Q5.3: 5 integer bits + 3 fractional bits = range [0, 15.875]
        return t_max / 15.875


def calibrate_activation_ranges(model, calib_loader, device='cpu'):
    """Run N calibration samples through the model to determine activation ranges."""
    observer = ActivationObserver()
    model.eval()

    # We need to capture activations at each layer output
    # Monkey-patch forward to capture intermediate outputs
    layer_outputs = {}

    def make_hook(name):
        def hook(module, input, output):
            observer.observe(name, output)
        return hook

    hooks = []
    hooks.append(model.conv1.register_forward_hook(make_hook('C1')))
    hooks.append(model.conv2.register_forward_hook(make_hook('C3')))
    hooks.append(model.conv3.register_forward_hook(make_hook('C5')))

    # S2 and S4 don't have dedicated modules (functional max_pool2d)
    # but their ranges will be same or smaller than preceding conv output
    # F6 and OUT are linear layers

    # Register hooks for linear layers
    hooks.append(model.fc1.register_forward_hook(make_hook('F6')))
    hooks.append(model.fc2.register_forward_hook(make_hook('OUT')))

    print(f"Calibrating activations on {len(calib_loader.dataset)} samples...")
    with torch.no_grad():
        for batch_idx, (data, _) in enumerate(calib_loader):
            data = data.to(device)
            _ = model(data)
            if (batch_idx + 1) % 50 == 0:
                print(f"  Calibrated {batch_idx + 1}/{len(calib_loader)} batches")

    # Remove hooks
    for h in hooks:
        h.remove()

    # Add S2 and S4 ranges (same as preceding conv output for ReLU)
    if 'C1' in observer.ranges:
        c1_min, c1_max = observer.ranges['C1']
        observer.ranges['S2'] = (0, c1_max)  # MaxPool, ReLU keeps non-negative
    if 'C3' in observer.ranges:
        c3_min, c3_max = observer.ranges['C3']
        observer.ranges['S4'] = (0, c3_max)

    return observer


def generate_golden_test_vectors(model, test_images, test_labels, scales, device='cpu'):
    """Generate golden reference outputs for hardware verification."""
    results = []
    model.eval()

    for idx, (img, label) in enumerate(zip(test_images, test_labels)):
        # img is [1, 1, 32, 32] — MNIST transform already pads to 32x32
        img = img.to(device)

        with torch.no_grad():
            output = model(img)

        # output shape: [1, 10] -> squeeze to [10]
        scores = output.squeeze().cpu().numpy()

        # Ensure scores is 1D of size 10
        if scores.ndim != 1 or scores.shape[0] != 10:
            print(f"  WARNING: unexpected output shape {output.shape}, scores shape {scores.shape}")
            scores = scores.flatten()[:10]

        predicted = int(np.argmax(scores))
        top_score = float(scores[predicted])

        results.append({
            'index': idx,
            'true_label': int(label),
            'predicted': predicted,
            'scores': scores.tolist(),
            'correct': predicted == label,
        })

        print(f"  Test image {idx}: label={label}, predicted={predicted}, "
              f"top_score={top_score:.4f}, {'✓' if predicted == label else '✗'}")

    return results


def export_image_as_header(img_32x32, filename, img_idx):
    """Export a 32x32 MNIST image as a uint8 C header for HLS testbench."""
    img_np = img_32x32.squeeze().cpu().numpy()
    # MNIST is normalized with mean=0.1307, std=0.3081, so denormalize
    img_np = img_np * 0.3081 + 0.1307
    # Scale to 8-bit unsigned [0, 255]
    img_uint8 = np.clip(np.round(img_np * 255), 0, 255).astype(np.uint8)

    with open(filename, 'w') as f:
        f.write(f'// MNIST test image {img_idx} (32x32 grayscale, uint8)\n')
        f.write(f'// Auto-generated by quantize_export.py\n')
        f.write(f'#pragma once\n\n')
        f.write(f'#include <stdint.h>\n\n')
        f.write(f'const uint8_t test_image_{img_idx}[32][32] = {{\n')
        for row in range(32):
            vals = ', '.join(str(int(v)) for v in img_uint8[row])
            f.write(f'    {{ {vals} }},\n')
        f.write('};\n')

    print(f"  Wrote test image: {filename}")


def main():
    # Load trained model
    model = load_model(MODEL_PATH)

    # Load MNIST calibration data
    from torchvision import datasets, transforms
    transform = transforms.Compose([
        transforms.Pad(2),
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])
    train_dataset = datasets.MNIST(
        root='./data', train=True, download=False, transform=transform
    )
    test_dataset = datasets.MNIST(
        root='./data', train=False, download=False, transform=transform
    )
    calib_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=128, shuffle=True, num_workers=2
    )

    # Calibrate activation ranges
    observer = calibrate_activation_ranges(model, calib_loader)
    print("\nActivation ranges (float32):")
    for name in ['C1', 'S2', 'C3', 'S4', 'C5', 'F6', 'OUT']:
        if name in observer.ranges:
            r_min, r_max = observer.ranges[name]
            scale = observer.get_scale(name)
            print(f"  {name:6s}: [{r_min:+.4f}, {r_max:+.4f}], Q5.3 scale = {scale:.6f}")

    # Quantize weights layer by layer
    print("\nQuantizing weights...")
    weight_data = {}  # name -> (q_weights, q_bias, w_scale, a_scale)

    # C1: Conv2d(1,6,5) weights: [6,1,5,5], bias: [6]
    layer_names = [
        ('conv1', 'c1', 'C1'),
        ('conv2', 'c3', 'C3'),
        ('conv3', 'c5', 'C5'),
        ('fc1',   'f6', 'F6'),
        ('fc2',   'out', 'OUT'),
    ]

    for param_name, prefix, act_name in layer_names:
        layer = dict(model.named_modules())[param_name]
        w = layer.weight.data
        b = layer.bias.data

        q_w, w_scale = quantize_weight_tensor(w)
        a_scale = observer.get_scale(act_name)
        q_b = quantize_bias_tensor(b, w_scale, a_scale)

        weight_data[prefix] = {
            'q_w': q_w,
            'q_b': q_b,
            'w_scale': w_scale,
            'a_scale': a_scale,
            'w_shape': list(w.shape),
            'b_shape': list(b.shape),
        }

        # Compute weight compression ratio
        original_bytes = w.numel() * 4  # float32
        quantized_bytes = q_w.nbytes + q_b.nbytes  # int8 + int32
        print(f"  {prefix}: weights {list(w.shape)} ({original_bytes}B -> {quantized_bytes}B, "
              f"{original_bytes/quantized_bytes:.1f}x), w_scale={w_scale:.6f}, a_scale={a_scale:.6f}")

    # Export weight headers
    os.makedirs(WEIGHTS_DIR, exist_ok=True)
    print(f"\nExporting weight headers to {WEIGHTS_DIR}...")

    for prefix in ['c1', 'c3', 'c5', 'f6', 'out']:
        d = weight_data[prefix]
        arrays = [
            {
                'arr': d['q_w'],
                'name': f'{prefix}_w',
                'dtype': 'int8_t',
            },
            {
                'arr': d['q_b'],
                'name': f'{prefix}_b',
                'dtype': 'int32_t',
            },
        ]
        write_weight_header(os.path.join(WEIGHTS_DIR, f'{prefix}_w.h'), [arrays[0]])
        write_weight_header(os.path.join(WEIGHTS_DIR, f'{prefix}_b.h'), [arrays[1]])

    # Also write a combined header that includes all
    with open(os.path.join(WEIGHTS_DIR, 'weights.h'), 'w') as f:
        f.write('// Combined LeNet-5 weight includes\n')
        f.write('#pragma once\n\n')
        for prefix in ['c1', 'c3', 'c5', 'f6', 'out']:
            f.write(f'#include "{prefix}_w.h"\n')
            f.write(f'#include "{prefix}_b.h"\n')

    # Save scale info for HLS
    scale_info = {}
    for prefix, d in weight_data.items():
        scale_info[f'{prefix}_w_scale'] = float(d['w_scale'])
        scale_info[f'{prefix}_a_scale'] = float(d['a_scale'])
        scale_info[f'{prefix}_w_shape'] = d['w_shape']
        scale_info[f'{prefix}_b_shape'] = d['b_shape']

    with open(os.path.join(WEIGHTS_DIR, 'scales.json'), 'w') as f:
        json.dump(scale_info, f, indent=2)

    # Generate golden test vectors
    print("\nGenerating golden test vectors...")
    # Pick test images (digits 0-9) using dataset indexing
    # Find one example of each digit in the test set
    test_images_by_digit = {}
    for i in range(len(test_dataset)):
        img, label = test_dataset[i]
        digit = int(label)
        if digit not in test_images_by_digit:
            test_images_by_digit[digit] = img  # img shape: [1, 28, 28]
        if len(test_images_by_digit) == 10:
            break

    test_images = []
    test_labels = []
    for digit in range(10):
        img = test_images_by_digit[digit]
        # Add batch dimension: [1, 28, 28] -> [1, 1, 28, 28]
        img = img.unsqueeze(0) if img.dim() == 3 else img
        test_images.append(img)
        test_labels.append(digit)

    golden_results = generate_golden_test_vectors(model, test_images, test_labels, weight_data)

    # Export test images as C headers for HLS testbench
    test_img_dir = os.path.join(os.path.dirname(__file__), '..', 'hls', 'lenet5_accel', 'tb')
    os.makedirs(test_img_dir, exist_ok=True)
    for i, (img, label) in enumerate(zip(test_images, test_labels)):
        fname = os.path.join(test_img_dir, f'test_image_{i}.h')
        export_image_as_header(img, fname, i)

    # Export expected outputs
    expected_outputs = {}
    for r in golden_results:
        expected_outputs[f'image_{r["index"]}'] = {
            'true_label': r['true_label'],
            'predicted': r['predicted'],
            'scores': r['scores'],
            'correct': r['correct'],
        }

    with open(os.path.join(test_img_dir, 'expected_outputs.json'), 'w') as f:
        json.dump(expected_outputs, f, indent=2)

    # Summary
    num_correct = sum(1 for r in golden_results if r['correct'])
    print(f"\nGolden test accuracy: {num_correct}/{len(golden_results)} ({100*num_correct/len(golden_results):.1f}%)")
    print(f"\nAll weight files exported to: {os.path.abspath(WEIGHTS_DIR)}")
    print("Phase 1 complete!")

    return 0


if __name__ == '__main__':
    sys.exit(main())
