// Combined LeNet-5 weight includes
// Auto-generated by quantize_export.py
#pragma once

#include <ap_int.h>

// Include all weight and bias files from weights directory
#include "weights/c1_w.h"
#include "weights/c1_b.h"
#include "weights/c3_w.h"
#include "weights/c3_b.h"
#include "weights/c5_w.h"
#include "weights/c5_b.h"
#include "weights/f6_w.h"
#include "weights/f6_b.h"
#include "weights/out_w.h"
#include "weights/out_b.h"
