// Auto-generated LeNet-5 weight file
// Do not edit manually
#pragma once

#include <ap_int.h>

// Auto-generated by quantize_export.py
// c1_b: shape (6,), dtype int32
const ap_int<32> c1_b[6] = {
    -26, -36, 17, 1, -64, -38,
};
