// Auto-generated LeNet-5 weight file
// Do not edit manually
#pragma once

#include <ap_int.h>

// Auto-generated by quantize_export.py
// c3_b: shape (16,), dtype int32
const ap_int<32> c3_b[16] = {
    -17, -4, -20, -19, 3, -17, 3, -19, -20, -17, -44, -13, -17, -14, -1, -21,
};
