// Auto-generated LeNet-5 weight file
// Do not edit manually
#pragma once

#include <ap_int.h>

// Auto-generated by quantize_export.py
// f6_b: shape (84,), dtype int32
const ap_int<32> f6_b[84] = {
    3, 12, 4, 12, -6, 5, -1, 2, 0, -9, -4, 1, 16, -3, 12, 3,
    3, -2, -2, -8, 9, 15, 0, -8, -1, 7, 2, 5, -2, 0, -2, 1,
    1, 6, -2, 3, -4, 0, 5, -9, 16, -5, -3, 12, -2, -7, 4, 9,
    11, 4, 0, -10, -4, 0, 10, -2, 4, 7, -4, -5, -1, 1, 5, 4,
    -3, -17, 3, 1, -1, 0, -4, -3, 21, -1, -5, -3, 0, 6, -6, -2,
    -3, -1, -1, 0,
};
