// Auto-generated LeNet-5 weight file
// Do not edit manually
#pragma once

#include <ap_int.h>

// Auto-generated by quantize_export.py
// out_b: shape (10,), dtype int32
const ap_int<32> out_b[10] = {
    1, 9, -7, -5, 2, 1, -2, -2, 7, -4,
};
