`timescale 1ns / 1ps

`define TB_CONV_ACCEL_CORE_MODULE tb_conv_accel_core_axi_lite_axis_stream_conv8_3x3_raw_hwc_ext_tile0_cout16
`define TB_CONV_ACCEL_CORE_USE_AXI_LITE
`define TB_CONV_ACCEL_CORE_USE_AXIS_STREAM
`define TB_CONV_ACCEL_CORE_BATCH_STREAM
`define TB_CONV_ACCEL_CORE_RAW_HWC_IFM
`define TB_CONV_ACCEL_CORE_USE_EXTERNAL_GOLDEN
`define TB_CONV_ACCEL_CORE_CENTER_EXTERNAL_IFM
`define TB_CONV_ACCEL_CORE_ROWS 18
`define TB_CONV_ACCEL_CORE_COLS 8
`define TB_CONV_ACCEL_CORE_IFM_BANKS 2
`define TB_CONV_ACCEL_CORE_CIN 256
`define TB_CONV_ACCEL_CORE_FM_W 13
`define TB_CONV_ACCEL_CORE_FM_H 13
`define TB_CONV_ACCEL_CORE_OFM_W 13
`define TB_CONV_ACCEL_CORE_OFM_H 13
`define TB_CONV_ACCEL_CORE_COUT_TOTAL 16
`define TB_CONV_ACCEL_CORE_PAD 1
`define TB_CONV_ACCEL_CORE_STRIDE 1
`define TB_CONV_ACCEL_CORE_INPUT_ZP 8'd13
`define TB_CONV_ACCEL_CORE_TILE_OY_BASE 0
`define TB_CONV_ACCEL_CORE_TILE_OFM_H 4
`define TB_CONV_ACCEL_CORE_TILE_PIXEL_BASE 0
`define TB_CONV_ACCEL_CORE_TILE_COUNT 1
`define TB_CONV_ACCEL_CORE_IFM_D 64
`define TB_CONV_ACCEL_CORE_IFM_AW 6
`define TB_CONV_ACCEL_CORE_PSUM_D 128
`define TB_CONV_ACCEL_CORE_PSUM_AW 7
`define TB_CONV_ACCEL_CORE_PSUM_BUF_AW 6
`define TB_CONV_ACCEL_CORE_PSUM_BUF_DEPTH 64
`define TB_CONV_ACCEL_CORE_OFM_ADDR_W 16
`define TB_CONV_ACCEL_CORE_OFM_FIFO_DEPTH 64
`define TB_CONV_ACCEL_CORE_OFM_FIFO_AW 6
`define TB_CONV_ACCEL_CORE_HWC_CACHE_AW 14
`define TB_CONV_ACCEL_CORE_HWC_CACHE_DEPTH 13312
`define TB_CONV_ACCEL_CORE_HWC_CACHE_STRIPES 4
`define TB_CONV_ACCEL_CORE_QUANT_MULT 16'd22396
`define TB_CONV_ACCEL_CORE_QUANT_SHIFT 4'd8
`define TB_CONV_ACCEL_CORE_QUANT_ZP 8'd63
`define TB_CONV_ACCEL_CORE_ACT_MODE 2
`define TB_CONV_ACCEL_CORE_IFM_MEM "D:/MPSoC/python_prj/rtl_golden/facemask_chain_conv0_conv8_rtl/08_head_conv8_3x3/xsim_mem_cout16/ifm_u8_hwc.mem"
`define TB_CONV_ACCEL_CORE_WEIGHT_MEM "D:/MPSoC/python_prj/rtl_golden/facemask_chain_conv0_conv8_rtl/08_head_conv8_3x3/xsim_mem_cout16/weight_kco_s8.mem"
`define TB_CONV_ACCEL_CORE_BIAS_MEM "D:/MPSoC/python_prj/rtl_golden/facemask_chain_conv0_conv8_rtl/08_head_conv8_3x3/xsim_mem_cout16/bias_i32.mem"
`define TB_CONV_ACCEL_CORE_ACT_LUT_MEM "D:/MPSoC/python_prj/rtl_golden/facemask_chain_conv0_conv8_rtl/08_head_conv8_3x3/xsim_mem_cout16/activation_lut_u8.mem"
`define TB_CONV_ACCEL_CORE_GOLDEN_MEM "D:/MPSoC/python_prj/rtl_golden/facemask_chain_conv0_conv8_rtl/08_head_conv8_3x3/xsim_mem_cout16/golden_ofm_u8_hwc.mem"
`define TB_CONV_ACCEL_CORE_TIMEOUT 20000000
`define TB_CONV_ACCEL_CORE_PROGRESS_PRINT
`define TB_CONV_ACCEL_CORE_COLTRACE
`define TB_CONV_ACCEL_CORE_PROGRESS_INTERVAL 50000

`include "tb_conv_accel_core_realistic_small.v"
