`define TB_CONV_ACCEL_CORE_MODULE tb_conv_accel_core_ps_driver
`define TB_CONV_ACCEL_CORE_COLS 4
`define TB_CONV_ACCEL_CORE_FM_W 8
`define TB_CONV_ACCEL_CORE_FM_H 8
`define TB_CONV_ACCEL_CORE_OFM_W 8
`define TB_CONV_ACCEL_CORE_OFM_H 8
`define TB_CONV_ACCEL_CORE_COUT_TOTAL 18
`define TB_CONV_ACCEL_CORE_PAD 1
`define TB_CONV_ACCEL_CORE_STRIDE 1
`define TB_CONV_ACCEL_CORE_TILE_COUNT 3
`define TB_CONV_ACCEL_CORE_TILE_OY_BASE 0
`define TB_CONV_ACCEL_CORE_TILE_OFM_H 3
`define TB_CONV_ACCEL_CORE_TILE_PIXEL_BASE 0
`define TB_CONV_ACCEL_CORE_TILE1_OY_BASE 3
`define TB_CONV_ACCEL_CORE_TILE1_OFM_H 3
`define TB_CONV_ACCEL_CORE_TILE1_PIXEL_BASE 24
`define TB_CONV_ACCEL_CORE_TILE2_OY_BASE 6
`define TB_CONV_ACCEL_CORE_TILE2_OFM_H 2
`define TB_CONV_ACCEL_CORE_TILE2_PIXEL_BASE 48
`define TB_CONV_ACCEL_CORE_TIMEOUT 260000

`include "tb_conv_accel_core_realistic_small.v"
