`timescale 1ns / 1ps

`define TB_CONV_ACCEL_CORE_MODULE tb_conv_accel_core_axi_lite_axis_stream_native1x1_small
`define TB_CONV_ACCEL_CORE_USE_AXI_LITE
`define TB_CONV_ACCEL_CORE_USE_AXIS_STREAM
`define TB_CONV_ACCEL_CORE_BATCH_STREAM
`define TB_CONV_ACCEL_CORE_KERNEL_1X1 1
`define TB_CONV_ACCEL_CORE_IFM_U8_FROM_CENTERED
`define TB_CONV_ACCEL_CORE_ROWS 18
`define TB_CONV_ACCEL_CORE_COLS 8
`define TB_CONV_ACCEL_CORE_IFM_BANKS 2
`define TB_CONV_ACCEL_CORE_CIN 20
`define TB_CONV_ACCEL_CORE_FM_W 3
`define TB_CONV_ACCEL_CORE_FM_H 2
`define TB_CONV_ACCEL_CORE_OFM_W 3
`define TB_CONV_ACCEL_CORE_OFM_H 2
`define TB_CONV_ACCEL_CORE_COUT_TOTAL 10
`define TB_CONV_ACCEL_CORE_PAD 0
`define TB_CONV_ACCEL_CORE_STRIDE 1
`define TB_CONV_ACCEL_CORE_INPUT_ZP 8'd7
`define TB_CONV_ACCEL_CORE_TILE_OY_BASE 0
`define TB_CONV_ACCEL_CORE_TILE_OFM_H 2
`define TB_CONV_ACCEL_CORE_TILE_PIXEL_BASE 0
`define TB_CONV_ACCEL_CORE_TILE_COUNT 1
`define TB_CONV_ACCEL_CORE_IFM_D 16
`define TB_CONV_ACCEL_CORE_IFM_AW 4
`define TB_CONV_ACCEL_CORE_PSUM_D 32
`define TB_CONV_ACCEL_CORE_PSUM_AW 5
`define TB_CONV_ACCEL_CORE_PSUM_BUF_AW 3
`define TB_CONV_ACCEL_CORE_PSUM_BUF_DEPTH 8
`define TB_CONV_ACCEL_CORE_OFM_ADDR_W 8
`define TB_CONV_ACCEL_CORE_OFM_FIFO_DEPTH 16
`define TB_CONV_ACCEL_CORE_OFM_FIFO_AW 4
`define TB_CONV_ACCEL_CORE_QUANT_MULT 16'd32767
`define TB_CONV_ACCEL_CORE_QUANT_SHIFT 4'd0
`define TB_CONV_ACCEL_CORE_QUANT_ZP 8'd0
`define TB_CONV_ACCEL_CORE_TIMEOUT 300000

`include "tb_conv_accel_core_realistic_small.v"
