`timescale 1ns / 1ps

`define TB_CONV_ACCEL_CORE_MODULE tb_conv_accel_core_axi_lite_full_stream_input_zp
`define TB_CONV_ACCEL_CORE_USE_AXI_LITE
`define TB_CONV_ACCEL_CORE_USE_FULL_STREAM
`define TB_CONV_ACCEL_CORE_USE_BW_STREAM
`define TB_CONV_ACCEL_CORE_IFM_U8_FROM_CENTERED
`define TB_CONV_ACCEL_CORE_INPUT_ZP 8'd36
`define TB_CONV_ACCEL_CORE_COLS 4
`define TB_CONV_ACCEL_CORE_ROWS 18
`define TB_CONV_ACCEL_CORE_IFM_BANKS 5
`define TB_CONV_ACCEL_CORE_CIN 16
`define TB_CONV_ACCEL_CORE_FM_W 8
`define TB_CONV_ACCEL_CORE_FM_H 8
`define TB_CONV_ACCEL_CORE_OFM_W 8
`define TB_CONV_ACCEL_CORE_OFM_H 8
`define TB_CONV_ACCEL_CORE_COUT_TOTAL 18
`define TB_CONV_ACCEL_CORE_IFM_D 256
`define TB_CONV_ACCEL_CORE_IFM_AW 8
`define TB_CONV_ACCEL_CORE_PSUM_D 256
`define TB_CONV_ACCEL_CORE_PSUM_AW 8
`define TB_CONV_ACCEL_CORE_PSUM_BUF_AW 6
`define TB_CONV_ACCEL_CORE_PSUM_BUF_DEPTH 64
`define TB_CONV_ACCEL_CORE_OFM_FIFO_DEPTH 64
`define TB_CONV_ACCEL_CORE_OFM_FIFO_AW 6
`define TB_CONV_ACCEL_CORE_TIMEOUT 200000

`include "tb_conv_accel_core_realistic_small.v"
