`define TB_CONV_ACCEL_CORE_MODULE tb_conv_accel_core_spatial_tile
`define TB_CONV_ACCEL_CORE_COLS 4
`define TB_CONV_ACCEL_CORE_FM_W 8
`define TB_CONV_ACCEL_CORE_FM_H 8
`define TB_CONV_ACCEL_CORE_OFM_W 8
`define TB_CONV_ACCEL_CORE_OFM_H 8
`define TB_CONV_ACCEL_CORE_COUT_TOTAL 18
`define TB_CONV_ACCEL_CORE_PAD 1
`define TB_CONV_ACCEL_CORE_STRIDE 1
`define TB_CONV_ACCEL_CORE_TILE_OY_BASE 2
`define TB_CONV_ACCEL_CORE_TILE_OFM_H 3
`define TB_CONV_ACCEL_CORE_TILE_PIXEL_BASE 16
`define TB_CONV_ACCEL_CORE_TIMEOUT 80000

`include "tb_conv_accel_core_realistic_small.v"
